
#=====================================================
# VERBOSE
#=====================================================
# Verbose (OFF)
/gate/verbose Physic 0
/gate/verbose Cuts 0
/gate/verbose SD 0
/gate/verbose Actions 0
/gate/verbose Actor 0
/gate/verbose Step 0
/gate/verbose Error 0
/gate/verbose Warning 0
/gate/verbose Output 0
/gate/verbose Beam 0
/gate/verbose Volume 0
/gate/verbose Image 0
/gate/verbose Geometry 0
/gate/verbose Core 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

#=====================================================
# DATABASE
#=====================================================

/gate/geometry/setMaterialDatabase              data/GateMaterials.db

#=====================================================
# WORLD 5x5x5 m3
#=====================================================


/gate/world/setMaterial Air
/gate/world/geometry/setXLength 5.0 m
/gate/world/geometry/setYLength 5.0 m
/gate/world/geometry/setZLength 5.0 m
/gate/world/vis/setVisible 0



#=====================================================
# WATER TANK (USELESS HERE)
#=====================================================

/gate/world/daughters/name waterTank
/gate/world/daughters/insert box
/gate/waterTank/geometry/setXLength 30 cm
/gate/waterTank/geometry/setYLength 30 cm
/gate/waterTank/geometry/setZLength 30 cm


#=====================================================
# FAKE LINAC
#=====================================================

# Gantry (mylinac). 
/gate/world/daughters/name mylinac
/gate/world/daughters/insert box
/gate/mylinac/setMaterial Air
/gate/mylinac/geometry/setXLength 2.2 m  
/gate/mylinac/geometry/setYLength 1.25 m
/gate/mylinac/geometry/setZLength 2.2 m
/gate/mylinac/placement/setRotationAxis 0 0 1 
/gate/mylinac/vis/setColor red
/gate/mylinac/vis/setVisible 0
#  Linac Head 
/gate/mylinac/daughters/name myLinacHead
/gate/mylinac/daughters/insert box
/gate/myLinacHead/setMaterial Air
/gate/myLinacHead/geometry/setXLength 1.5 m  
/gate/myLinacHead/geometry/setYLength 1.2 m
/gate/myLinacHead/geometry/setZLength 1.5 m
/gate/myLinacHead/placement/setRotationAxis 0 1 0 
/gate/myLinacHead/placement/setRotationAngle 180.000 deg
/gate/myLinacHead/vis/setColor green
/gate/myLinacHead/vis/setVisible 0

#=====================================================
# DEFINITION OF BOXES TO ATTACH PHSP FILES
#=====================================================



# - - - - - - - - - - - - - - - - - - -
# FIRST ACTOR IS MADE TO ATTACH  NATIVE IAEA FILES
# - - - - - - - - - - - - - - - - - - -
/gate/myLinacHead/daughters/name inputNativeIAEAplan
/gate/myLinacHead/daughters/insert box
/gate/inputNativeIAEAplan/setMaterial Air
/gate/inputNativeIAEAplan/geometry/setXLength 0.15 m
/gate/inputNativeIAEAplan/geometry/setYLength 0.15 m
/gate/inputNativeIAEAplan/geometry/setZLength 0.01 m
/gate/inputNativeIAEAplan/placement/setRotationAxis 1 0 0
/gate/inputNativeIAEAplan/placement/setRotationAngle 90.0 deg
/gate/inputNativeIAEAplan/placement/setTranslation 0.0 0.0 0.0 mm
/gate/inputNativeIAEAplan/vis/setVisible 0
/gate/inputNativeIAEAplan/vis/forceSolid


# - - - - - - - - - - - - - - - - - - -
# SECOND IS MADE TO STORE PARTICLES IN A
# FIRST SIMULATION AND TO LAUNCH THEM IN A
# SECOND ONE
# - - - - - - - - - - - - - - - - - - -
/gate/myLinacHead/daughters/name outPhSp
/gate/myLinacHead/daughters/insert box
/gate/outPhSp/setMaterial Air
/gate/outPhSp/placement/setTranslation 0.0 -469.0 0.0 mm
/gate/outPhSp/geometry/setXLength 400.0 mm
/gate/outPhSp/geometry/setYLength 1 cm
/gate/outPhSp/geometry/setZLength 400.0 mm
/gate/outPhSp/vis/setColor magenta
/gate/outPhSp/vis/forceSolid
/gate/outPhSp/vis/setVisible 1



# ---------- PHYSICS  ---------------


/gate/physics/addPhysicsList emlivermore

/gate/physics/Gamma/SetCutInRegion      world 50 mm
/gate/physics/Electron/SetCutInRegion   world 15 mm
/gate/physics/Positron/SetCutInRegion   world 15 mm

/gate/physics/Gamma/SetCutInRegion      mylinac 50 mm
/gate/physics/Electron/SetCutInRegion   mylinac 15 mm
/gate/physics/Positron/SetCutInRegion   mylinac 15 mm

/gate/physics/Gamma/SetCutInRegion      waterTank 0.1 mm
/gate/physics/Electron/SetCutInRegion   waterTank 0.01 mm
/gate/physics/Positron/SetCutInRegion   waterTank 0.01 mm

/gate/physics/displayCuts
/gate/physics/print output/physics.txt

/gate/mylinac/placement/setRotationAngle -0.000 deg
/gate/mylinac/placement/setTranslation 0.000 1000.000 0.0 mm


#=====================================================
# OUTPUT ACTORS
#=====================================================


# To use if no output is required
#/gate/output/allowNoOutput

# ------------------- IAEA format ------------------------
# an IAEAphsp file is created in air attached to "outPhsp"
# output file is output/myIAEA.IAEAphsp
# This file can be placed in data/ to be use as an input

/gate/actor/addActor PhaseSpaceActor IAEAPhaseSpace
/gate/actor/IAEAPhaseSpace/save output/myIAEA.IAEAphsp
/gate/actor/IAEAPhaseSpace/attachTo outPhSp
/gate/actor/IAEAPhaseSpace/enableEkine true
/gate/actor/IAEAPhaseSpace/enableXPosition true
/gate/actor/IAEAPhaseSpace/enableYPosition true
/gate/actor/IAEAPhaseSpace/enableZPosition true
/gate/actor/IAEAPhaseSpace/enableXDirection true
/gate/actor/IAEAPhaseSpace/enableYDirection true
/gate/actor/IAEAPhaseSpace/enableZDirection true
/gate/actor/IAEAPhaseSpace/enableProductionVolume false
/gate/actor/IAEAPhaseSpace/enableProductionProcess false
/gate/actor/IAEAPhaseSpace/enableParticleName true
/gate/actor/IAEAPhaseSpace/enableWeight true
# Store coordinates in the actor coordinates
/gate/actor/IAEAPhaseSpace/useVolumeFrame true
# Warning : set this line to true make the particles generated twice
# when the output file is used as an input
/gate/actor/IAEAPhaseSpace/storeSecondaries false


# ------------------- ROOT format ------------------------
# an ROOT file is created in air attached to "outPhsp"
# output file is output/output-PhS-g.root
# Phase space storage (a PhS for gamma)
/gate/actor/addActor                         PhaseSpaceActor PhS_g
/gate/actor/PhS_g/attachTo                   outPhSp
/gate/actor/PhS_g/save                       output/output-PhS-g.root
/gate/actor/PhS_g/enableParticleName         false
/gate/actor/PhS_g/enableProductionVolume     false
/gate/actor/PhS_g/enableProductionProcess    false
/gate/actor/PhS_g/useVolumeFrame             true
/gate/actor/PhS_g/addFilter                  particleFilter
/gate/actor/PhS_g/particleFilter/addParticle gamma
/gate/actor/PhS_g/enableZPosition            true


# Visu (QT)
/vis/open                             OGLI
/vis/drawVolume
/vis/viewer/flush
/tracking/storeTrajectory             1
/vis/scene/add/trajectories 
/vis/scene/endOfEventAction           accumulate
/vis/scene/add/axes
/gate/geometry/setMaterialDatabase data/TBMaterials.db

/gate/run/initialize

#=====================================================
# INPUT FILES
#=====================================================


# USE ONLY ONE OF THESE INPUT PHASE SPACE FILES
# Uncomment group of three lines to enable
# Comment the other one


# 1. Particles from a native IAEA files attach to first box
# inputNativeIAEAplan
/gate/source/addSource MyBeam phaseSpace
/gate/source/MyBeam/addPhaseSpaceFile data/1000p.IAEAphsp
/gate/source/MyBeam/attachTo inputNativeIAEAplan

#  2. Particles from a IAE File created by a 
#  previous simulation attach to the second box 'outPhSp
#/gate/source/addSource MyBeam phaseSpace
#/gate/source/MyBeam/addPhaseSpaceFile data/myIAEA.IAEAphsp
#/gate/source/MyBeam/attachTo outPhSp




#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/setTotalNumberOfPrimaries 10000
/gate/application/start
