
# Generate materials from Hounsfield units
/gate/HounsfieldMaterialGenerator/SetMaterialTable                  data/Schneider2000MaterialsTable.txt
/gate/HounsfieldMaterialGenerator/SetDensityTable                   data/Schneider2000DensitiesTable.txt
/gate/HounsfieldMaterialGenerator/SetDensityTolerance               0.1 g/cm3
/gate/HounsfieldMaterialGenerator/SetOutputMaterialDatabaseFilename data/patient-HUmaterials.db
/gate/HounsfieldMaterialGenerator/SetOutputHUMaterialFilename       data/patient-HU2mat.txt
/gate/HounsfieldMaterialGenerator/Generate

/gate/world/daughters/name                      phantom
/gate/world/daughters/insert                    ImageNestedParametrisedVolume

/gate/geometry/setMaterialDatabase              data/patient-HUmaterials.db
/gate/phantom/geometry/setHUToMaterialFile      data/patient-HU2mat.txt
/gate/phantom/geometry/setImage                 data/patient_CT.mhd

# Important because the mhd is not centered
#/gate/phantom/geometry/TranslateTheImageAtThisIsoCenter 0 0 0 mm
