/gate/source/addSource                                       Y90Source voxel
/gate/source/Y90Source/reader/insert                         image
/gate/source/Y90Source/imageReader/translator/insert         linear
/gate/source/Y90Source/imageReader/linearTranslator/setScale 1. Bq
/gate/source/Y90Source/imageReader/readFile                  data/patient_SPECT.mhd

# offset in mhd : -243.1 -243.1 -486.2
# voxel size 4.42
/gate/source/Y90Source/setPosition -243.1 -243.1 -486.2 mm
#/gate/source/Y90Source/TranslateTheSourceAtThisIsoCenter  0 0 0 mm

/gate/source/Y90Source/gps/particle ion
/gate/source/Y90Source/gps/ion      39 90 0 0
/gate/source/Y90Source/gps/angtype  iso
/gate/source/Y90Source/gps/centre   0. 0. 0. mm
/gate/source/Y90Source/gps/energy   0 MeV
